version: '3'

networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}

services:
  whoami:
    env_file:
      - ./.env

    image: ${IMAGE_NAME}

    hostname: ${HOST_NAME}

    labels:
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_NAME}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=https
      - traefik.http.routers.${SERVICE_NAME}.tls=true
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencrypt

    restart: unless-stopped
