
networks:
  global:

services:

  main:

    command:
      - --api=true
      - --api.dashboard=true

      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true

      - --certificatesresolvers.letsencrypt.acme.email=${CF_API_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entryPoints.https.http3
      - --entryPoints.https.http3.advertisedport=443

      - --providers.docker=true

      # !!! IMPORTANT! Comment out or delete next line in production! !!!
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

    env_file:
      - ./.env

    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CF_API_TOKEN}

    hostname: ${HOST_NAME}

    image: ${TRAEFIK_IMAGE}

    labels:
      - traefik.http.middlewares.auth.basicauth.usersFile=/etc/traefik/.htpasswd
      - traefik.http.middlewares.to-https.redirectscheme.scheme=https

      - traefik.http.routers.to-https.entrypoints=http
      - traefik.http.routers.to-https.middlewares=to-https
      - traefik.http.routers.to-https.rule=HostRegexp(`{host:.+}`)

      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.rule=Host(`${HOST_NAME}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.tls=true

    networks:
      - global

    ports:
      - 80:80
      - 443:443/tcp
      - 443:443/udp

    restart: unless-stopped

    volumes:
      - .htpasswd:/etc/traefik/.htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - acme:/letsencrypt

volumes:
  acme:

