
networks:
  default:
    external:
      name: ${DEFAULT_NETWORK}

services:

  whoami:

    env_file:
      - ./.env

    hostname: ${HOST_NAME}

    image: ${IMAGE_NAME}

    labels:
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=https
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${HOST_NAME}`)
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencrypt
      - traefik.http.routers.${SERVICE_NAME}.tls=true

    restart: unless-stopped
